version: '2'
services:
  app:
    container_name: apiprodutos
    image: api-produtos
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password123@db/api_produtos
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13.12-alpine
    container_name: db_postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=password123
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5